CXX = g++
INCLUDES = -I $(DEP_PATH) -I $(DEP_PATH)/colorado 
CPPFLAGS = -fPIC -Wall -Wextra -O3 $(INCLUDES)
LDFLAGS = -shared
RM = rm -f
TARGET_LIB = libColoradoAudio.so

CPP_SRCS = \
	stb-vorbis-dec.cpp \
	tremor-dec.cpp \
	audio-stream.cpp \
	audio.cpp \
	streamer.cpp \

CPP_OBJS = $(CPP_SRCS:.cpp=.o)

.PHONY: all
all: ${TARGET_LIB}

esound.h: ../sounds/*.ogg enum-resources.sh
	bash enum-resources.sh > $@

$(TARGET_LIB): esound.h $(CPP_OBJS)
	$(CXX) ${LDFLAGS} -o $@ $(CPP_OBJS)

$(CPP_SRCS:.cpp=.d):%.d:%.cpp
	$(CXX) $(CPPFLAGS) -MM $< > $@

include $(CPP_SRCS:.cpp=.d)

.PHONY: clean
clean:
	${RM} ${TARGET_LIB} ${CPP_OBJS} $(CPP_SRCS:.cpp=.d)
	
