#### PROJECT SETTINGS ####
# The name of the executable to be created
BIN_NAME := libcolorado_ecs.so
# Space-separated pkg-config libraries used by this project
LIBS = 
# Add additional include paths
INCLUDES = 
# General linker settings
LINK_FLAGS = -fPIC -shared
# Additional release-specific linker settings
RLINK_FLAGS = 
# Additional debug-specific linker settings
DLINK_FLAGS = 
#### END PROJECT SETTINGS ####

include ../Makefile.common
